### PR TITLE
Adding mjpeg

### PR DESCRIPTION
**Pull request by aous72**
Hi Sean,

It seems I misunderstood things.  I was thinking that the starting point for this is master, but it is not.

In any case, here I included 5 frames from the video sequence, starting at frame 10 (0-base).

I have modified the code, and added needed files.  Everything works, but the PSNR results are lower than what is in the paper. I checked that the parameters match those used in our paper.  That submission was using fgt2.  If you have the time could you please have a look, or let me know what you think.

Kind regards,
Aous

### CODE REVIEW

**Comment by seannz** [comment]
Hi Aous,

Hmm, could you try checking out commit number adc2925 from our internal repo and see if the MJPEG program works there? That one has the original code. I tried to look into it from home just now, but the codebase got quite large to clone and it's difficult for me to visualize results etc over ssh...

**Comment by aous72** [comment]
I went back all the way to 64f1620, when I first generated the results.  That one seems to generate results very close to the one we generated before, and used in the paper.  The one you suggested crashed Matlab.

**Comment by seannz** [comment]
Thanks for this Aous, shall I merge into master?

**Comment by aous72** [comment]
No, this final merge is just a correction and a simplification of a term. 
If you have the time, see why it is not producing the same results as before; the gap is rather large.

**Comment by seannz** [comment]
Hmm, how about we just upload the one that's working? We can leave out the scanning code etc.

**Comment by aous72** [comment]
I haven't tested the scanning code; I thought we will leave it out.
The working one uses fgt2. Is that alright with you?

**Comment by seannz** [comment]
I think doing the memory allocation from within the MEX file made the whole thing slow anyway (but now they have the benefit of not crashing often). For the MJPEG script, it might be better to let it crash if it needs to, haha.

**Comment by seannz** [comment]
That's fine. fgt2 is the version that writes back to the input argument memory (not ideal, but is fast).

**Comment by aous72** [comment]
Ok, I will prepare a commit and let you know.  The results with fgt2 is very close to paper's results but not exactly the same.

**Comment by seannz** [comment]
Okay, thanks! Also, I remember seeing an email from you regarding the parameter values you used for our final set of results (the last revision of the paper), but I can't seem to find them. If you find them, could you put them in the README? I'll keep looking as well.

**Comment by aous72** [comment]
Do you mean for one or both graphmain and graphmpeg?

**Comment by seannz** [comment]
I found the graph main ones (it was in my other email account...) and updated README accordingly. I don't think we ever talked about the graph mpeg parameters in the email? I'll have a look.

**Comment by aous72** [comment]
Hi Sean,

I committed the graphmpeg_fun.m that uses fgt2 together with the necessary file, for Linux and Windows.  Please review and check it in if you are happy, or let me know.  I also modified the README file; I put the parameters used.

Cheers,
Aous.

**Comment by seannz** [comment]
Thanks Aous!

**Pull request merged**
